# Cloud Build configuration for automatic deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/philgeps-crawler:$COMMIT_SHA', '.']
  
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/philgeps-crawler:$COMMIT_SHA']
  
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/philgeps-crawler:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/philgeps-crawler:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/philgeps-crawler:latest']
  
  # Deploy to Cloud Run (with or without volume mount based on DATABASE_TYPE)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # Check if we should use volume mount (for SQLite)
      if [[ "${_DATABASE_TYPE}" == "sqlite3" ]]; then
        echo "Deploying with GCS volume mount for SQLite..."
        
        # Update service configuration with actual values
        sed -e "s/PROJECT_ID/$PROJECT_ID/g" \
            -e "s/YOUR_BUCKET_NAME/${PROJECT_ID}-philgeps-data/g" \
            cloud-run-service.yaml > cloud-run-service-deploy.yaml
        
        # Deploy using the service configuration
        gcloud run services replace cloud-run-service-deploy.yaml \
          --region=${_REGION}
      else
        echo "Deploying without volume mount (using PostgreSQL)..."
        
        # Deploy normally without volume mount
        gcloud run deploy philgeps-crawler \
          --image=gcr.io/$PROJECT_ID/philgeps-crawler:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars="NODE_ENV=production,DATABASE_TYPE=${_DATABASE_TYPE},CRAWL_INTERVAL_MINUTES=60,REQUEST_DELAY_MS=5000,RUN_INITIAL_CRAWL=false,MAX_PAGES_TO_CRAWL=20,PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true,PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser,LOG_LEVEL=info,LOG_FORMAT=json,ENABLE_FULL_CRAWL=true,ENABLE_SCHEDULED_CRAWL=true,ENABLE_API=true,ENABLE_WEB_UI=true" \
          --memory=2Gi \
          --cpu=2 \
          --timeout=3600 \
          --max-instances=10
      fi

# Substitution variables (can be overridden)
substitutions:
  _REGION: asia-southeast1
  _DATABASE_TYPE: sqlite3  # Change to 'postgres' for PostgreSQL deployment

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Images to be pushed
images:
- 'gcr.io/$PROJECT_ID/philgeps-crawler:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/philgeps-crawler:latest'

# Timeout for the entire build
timeout: '1200s'